### PR TITLE
dont put your scale.com token in gh

### PR DESCRIPTION
**Pull request by planchon**

### CODE REVIEW

**Comment by planchon** [comment]
invalid this key as soon as you see the message :')

**Comment by fapont** [comment]
Use https://rtyley.github.io/bfg-repo-cleaner/ if you want to clean you repo and yes invalid this token unless you're a philanthropist

**Comment by planchon** [comment]
also, remove your openai key from the "bro server" commit
same problem

**Comment by evanmays** [comment]
Appreciate this!!

I happen to be a philanthropist

jk, but the scale account isn't connected to my credit card. It's using credits from the hackathon. And the OpenAI keys were promptly rotated. OpenAI themselves seems to be scanning repos

**Pull request closed without merging**
